/**
 * Deterministic synthetic OHLCV fixture data for the chart similarity engine (Phase 3EX-B).
 *
 * This is entirely synthetic: a clearly fake market/symbol, dates generated from a fixed
 * synthetic epoch (never the current date), and values generated by fixed trend + cyclical
 * arithmetic (never `Math.random()`). No real market values or real stock codes are used.
 * The cyclical component intentionally repeats every 40 bars so multiple historical windows
 * correlate with the most recent window, giving the scanner meaningful matches to find.
 */

import type { OhlcBar } from '../../lib/chartSimilarity/types';

const FIXTURE_MARKET = 'SYNTHETIC';
const FIXTURE_SYMBOL = 'SYNTH001';
const BAR_COUNT = 260;
const START_YEAR = 2001;
const START_MONTH_INDEX = 0; // January (UTC month index)
const START_DAY = 2;

const isWeekend = (date: Date): boolean => {
  const day = date.getUTCDay();
  return day === 0 || day === 6;
};

const buildSyntheticDates = (count: number): string[] => {
  const dates: string[] = [];
  const cursor = new Date(Date.UTC(START_YEAR, START_MONTH_INDEX, START_DAY));
  while (dates.length < count) {
    if (!isWeekend(cursor)) {
      const year = cursor.getUTCFullYear();
      const month = String(cursor.getUTCMonth() + 1).padStart(2, '0');
      const day = String(cursor.getUTCDate()).padStart(2, '0');
      dates.push(`${year}-${month}-${day}`);
    }
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  return dates;
};

const round2 = (value: number): number => Math.round(value * 100) / 100;

export const buildSyntheticOhlcvFixture = (): OhlcBar[] => {
  const dates = buildSyntheticDates(BAR_COUNT);
  const bars: OhlcBar[] = [];

  for (let i = 0; i < BAR_COUNT; i += 1) {
    const trend = 0.04 * i;
    const longCycle = 9 * Math.sin((2 * Math.PI * i) / 40);
    const shortCycle = 2.5 * Math.sin((2 * Math.PI * i) / 7) + 1.3 * Math.cos((2 * Math.PI * i) / 11);
    const close = round2(Math.max(5, 100 + trend + longCycle + shortCycle));

    const openOffset = 0.6 * Math.sin((2 * Math.PI * (i + 3)) / 9);
    const open = round2(Math.max(5, close - openOffset));

    const rangePad = 0.8 + Math.abs(Math.sin((2 * Math.PI * i) / 5));
    const high = round2(Math.max(open, close) + rangePad);
    const low = round2(Math.max(1, Math.min(open, close) - rangePad));

    const volume = Math.round(
      120000 + 15000 * Math.sin((2 * Math.PI * i) / 13) + 4000 * Math.cos((2 * Math.PI * i) / 21),
    );

    bars.push({
      market: FIXTURE_MARKET,
      symbol: FIXTURE_SYMBOL,
      date: dates[i],
      open,
      high,
      low,
      close,
      volume,
      adjusted: false,
      source: 'synthetic',
    });
  }

  return bars;
};
