-- Phase 3GG-T-HF2: durable, shared KIS access-token lifecycle (state + lease + fencing + events).
-- Apply via Supabase Dashboard > SQL Editor (do NOT execute via Claude Code).
-- Additive, forward-only. Server (service_role) is the ONLY intended caller.
-- No token plaintext is ever stored: only an AES-256-GCM envelope (ciphertext/iv/auth_tag) is persisted.
-- No user, account, order, balance, trade, or personal data is stored here (token lifecycle only).

-- ============================================================
-- Schema (server-only; already revoked from anon in the base migration)
-- ============================================================
create schema if not exists internal;

-- ============================================================
-- 8.1 TABLE: internal.kis_token_state  (one row per credential namespace / scope_key)
-- ============================================================
create table if not exists internal.kis_token_state (
  scope_key                 text primary key,
  provider                  text        not null default 'kis',
  status                    text        not null default 'empty'
    check (status in ('empty','valid','refresh_window','expired','invalidated','issuing','error')),
  token_ciphertext          text,
  token_iv                  text,
  token_auth_tag            text,
  encryption_key_version    integer     not null default 1,
  generation_id             uuid,
  issued_at                 timestamptz,
  expires_at                timestamptz,
  usable_until              timestamptz,
  last_issue_attempt_at     timestamptz,
  last_issue_success_at     timestamptz,
  last_forced_refresh_at    timestamptz,
  last_error_code           text,
  invalidated_generation_id uuid,
  lease_owner               text,
  lease_version             bigint      not null default 0,
  lease_acquired_at         timestamptz,
  lease_expires_at          timestamptz,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);
comment on table internal.kis_token_state is
  'Durable, shared KIS access-token state (one row per scope_key). Stores only an AES-256-GCM token envelope, never plaintext. Server/service_role only.';

-- ============================================================
-- 8.2 TABLE: internal.kis_token_event  (secret-safe lifecycle telemetry; metadata only)
-- ============================================================
create table if not exists internal.kis_token_event (
  event_id       bigint generated by default as identity primary key,
  scope_key      text        not null,
  occurred_at    timestamptz not null default now(),
  event_type     text        not null,
  generation_id  uuid,
  route_category text,
  deployment_id  text,
  instance_id    text,
  lock_wait_ms   integer,
  safe_error_code text,
  metadata       jsonb
);
comment on table internal.kis_token_event is
  'Secret-safe KIS token lifecycle events. Metadata only; never a token, ciphertext, key, header, or raw provider payload.';

create index if not exists kis_token_event_scope_time_idx
  on internal.kis_token_event (scope_key, occurred_at desc);

-- ============================================================
-- RLS (deny-all for browser roles; service_role bypasses RLS)
-- ============================================================
alter table internal.kis_token_state enable row level security;
alter table internal.kis_token_event enable row level security;
-- No anon/authenticated policies are created: browser roles get no access.

revoke all on table internal.kis_token_state from public, anon, authenticated;
revoke all on table internal.kis_token_event from public, anon, authenticated;

-- ============================================================
-- 8.3 RPC: internal.acquire_kis_token_lease
--   Atomic conditional lease acquisition with fencing (lease_version bump).
-- ============================================================
create or replace function internal.acquire_kis_token_lease(
  p_scope_key        text,
  p_lease_owner      text,
  p_lease_ttl_seconds integer
)
returns table (
  acquired         boolean,
  lease_version    bigint,
  lease_expires_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ttl integer := greatest(1, coalesce(p_lease_ttl_seconds, 20));
begin
  if p_scope_key is null or p_lease_owner is null then
    raise exception 'scope_key and lease_owner are required';
  end if;

  -- Ensure the state row exists (idempotent).
  insert into internal.kis_token_state (scope_key, status)
  values (p_scope_key, 'empty')
  on conflict (scope_key) do nothing;

  -- Conditional atomic acquisition (row lock serializes concurrent acquirers).
  return query
  update internal.kis_token_state as s
     set lease_owner       = p_lease_owner,
         lease_version     = s.lease_version + 1,
         lease_acquired_at = now(),
         lease_expires_at  = now() + make_interval(secs => v_ttl),
         updated_at        = now()
   where s.scope_key = p_scope_key
     and (s.lease_owner is null
          or s.lease_expires_at is null
          or s.lease_expires_at < now()
          or s.lease_owner = p_lease_owner)
  returning true, s.lease_version, s.lease_expires_at;

  if not found then
    return query
    select false, s.lease_version, s.lease_expires_at
      from internal.kis_token_state as s
     where s.scope_key = p_scope_key;
  end if;
end;
$$;
comment on function internal.acquire_kis_token_lease(text, text, integer) is
  'Atomically acquires the durable KIS token lease with fencing (increments lease_version). Server-side use only.';

-- ============================================================
-- 8.4 RPC: internal.release_kis_token_lease
--   Releases only when scope_key + lease_owner + lease_version all match.
-- ============================================================
create or replace function internal.release_kis_token_lease(
  p_scope_key     text,
  p_lease_owner   text,
  p_lease_version bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_released boolean := false;
begin
  update internal.kis_token_state as s
     set lease_owner      = null,
         lease_acquired_at = null,
         lease_expires_at  = null,
         updated_at        = now()
   where s.scope_key = p_scope_key
     and s.lease_owner = p_lease_owner
     and s.lease_version = p_lease_version;
  v_released := found;
  return v_released;
end;
$$;
comment on function internal.release_kis_token_lease(text, text, bigint) is
  'Releases the KIS token lease only for the current fencing owner/version. Server-side use only.';

-- ============================================================
-- 8.5 RPC: internal.store_kis_token_generation
--   Atomically stores the encrypted envelope AND releases the lease, fenced by owner+version.
-- ============================================================
create or replace function internal.store_kis_token_generation(
  p_scope_key      text,
  p_lease_owner    text,
  p_lease_version  bigint,
  p_generation_id  uuid,
  p_ciphertext     text,
  p_iv             text,
  p_auth_tag       text,
  p_key_version    integer,
  p_issued_at      timestamptz,
  p_expires_at     timestamptz,
  p_usable_until   timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_stored boolean := false;
begin
  update internal.kis_token_state as s
     set token_ciphertext       = p_ciphertext,
         token_iv               = p_iv,
         token_auth_tag         = p_auth_tag,
         encryption_key_version = coalesce(p_key_version, 1),
         generation_id          = p_generation_id,
         issued_at              = p_issued_at,
         expires_at             = p_expires_at,
         usable_until           = p_usable_until,
         status                 = 'valid',
         last_issue_success_at  = now(),
         last_error_code        = null,
         invalidated_generation_id = null,
         -- Store + release the lease atomically (fencing preserved via lease_version below).
         lease_owner            = null,
         lease_acquired_at      = null,
         lease_expires_at       = null,
         updated_at             = now()
   where s.scope_key = p_scope_key
     and s.lease_owner = p_lease_owner
     and s.lease_version = p_lease_version;
  v_stored := found;
  return v_stored;
end;
$$;
comment on function internal.store_kis_token_generation(text, text, bigint, uuid, text, text, text, integer, timestamptz, timestamptz, timestamptz) is
  'Atomically persists the encrypted KIS token generation and releases the lease, only for the current fencing owner/version. Rejects stale lease holders. Server-side use only.';

-- ============================================================
-- 8.6 RPC: internal.invalidate_kis_token_generation
--   Invalidates only when the stored generation matches the failed request's generation.
-- ============================================================
create or replace function internal.invalidate_kis_token_generation(
  p_scope_key     text,
  p_generation_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_invalidated boolean := false;
begin
  update internal.kis_token_state as s
     set status                    = 'invalidated',
         invalidated_generation_id = p_generation_id,
         last_forced_refresh_at    = now(),
         updated_at                = now()
   where s.scope_key = p_scope_key
     and s.generation_id = p_generation_id;
  v_invalidated := found;
  return v_invalidated;
end;
$$;
comment on function internal.invalidate_kis_token_generation(text, uuid) is
  'Invalidates the current KIS token generation ONLY when it matches the failed generation id (never clobbers a newer generation). Server-side use only.';

-- ============================================================
-- 8.7 RPC: internal.record_kis_token_event  (metadata-only telemetry insert)
-- ============================================================
create or replace function internal.record_kis_token_event(
  p_scope_key      text,
  p_event_type     text,
  p_generation_id  uuid,
  p_route_category text,
  p_deployment_id  text,
  p_instance_id    text,
  p_lock_wait_ms   integer,
  p_safe_error_code text,
  p_metadata       jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into internal.kis_token_event (
    scope_key, event_type, generation_id, route_category,
    deployment_id, instance_id, lock_wait_ms, safe_error_code, metadata
  ) values (
    p_scope_key, p_event_type, p_generation_id, p_route_category,
    p_deployment_id, p_instance_id, p_lock_wait_ms, p_safe_error_code, p_metadata
  );
end;
$$;
comment on function internal.record_kis_token_event(text, text, uuid, text, text, text, integer, text, jsonb) is
  'Inserts a secret-safe KIS token lifecycle event. Metadata only. Server-side use only.';

-- ============================================================
-- Grants: service_role only (browser roles get nothing)
-- ============================================================
grant usage on schema internal to service_role;
grant select on internal.kis_token_state to service_role;
grant select on internal.kis_token_event to service_role;

revoke all on function internal.acquire_kis_token_lease(text, text, integer) from public, anon, authenticated;
revoke all on function internal.release_kis_token_lease(text, text, bigint) from public, anon, authenticated;
revoke all on function internal.store_kis_token_generation(text, text, bigint, uuid, text, text, text, integer, timestamptz, timestamptz, timestamptz) from public, anon, authenticated;
revoke all on function internal.invalidate_kis_token_generation(text, uuid) from public, anon, authenticated;
revoke all on function internal.record_kis_token_event(text, text, uuid, text, text, text, integer, text, jsonb) from public, anon, authenticated;

grant execute on function internal.acquire_kis_token_lease(text, text, integer) to service_role;
grant execute on function internal.release_kis_token_lease(text, text, bigint) to service_role;
grant execute on function internal.store_kis_token_generation(text, text, bigint, uuid, text, text, text, integer, timestamptz, timestamptz, timestamptz) to service_role;
grant execute on function internal.invalidate_kis_token_generation(text, uuid) to service_role;
grant execute on function internal.record_kis_token_event(text, text, uuid, text, text, text, integer, text, jsonb) to service_role;
